### ISSUE TITLE
Route not matched when parameter includes "special" characters

### ISSUE THREAD

**Issue by chiefsmurph** [hyperapp/router#10]
considering these routes:
```
[
     ['/home', home],
     ['/query/:query', query],
     ['*', (state, actions) => {
         return (
             <b>{location.pathname}</b>
         );
     }]
]
```

when I navigate to `/query/Hot` hyperapp-router correctly matches the `query` route.
however when I navigate to `/query/Hot%20Pocket` it does not match the `query` route and instead falls back to the `*` route.

the same happens if there is `:`, `(`, or `)` in the query parameter whether or not the "special" characters are URI encoded.

**Comment by jbucaran** [comment]
@chiefsmurph Seems like some encoding is due. If you know how to solve the problem can you send a PR? The router now works with latest hyperapp! :)
