### ISSUE TITLE
Component-based router API

### ISSUE THREAD

**Issue by JorgeBucaran** [hyperapp/router#11]
Default router.

```jsx
app({
  view: [
    ["/", state => <h1>Hi.</h1>]
    ["*", state => <h1>404</h1>],
  ],
  mixins: [Router]
})
```

Component-based router (proposed syntax).

```jsx
<Router>
  <Route path="/" route={() => <h1>Hi.</h1>} />
  <Route path="*" route={() => <h1>404</h1>} />
</Router>
```

**Comment by jbucaran** [comment]
@SkaterDad @zaceno @lukejacksonn Thoughts? 🤔

**Comment by lukejacksonn** [comment]
How about calling it what is is..
```
<Router>
  <Route path="/" view={() => <h1>Hi.</h1>} />
  <Route path="*" view={() => <h1>404</h1>} />
</Router>
```
Are you experimenting with this anywhere (CodePen, etc.)?

**Comment by zaceno** [comment]
Is the `<Router>` to enclose various routes absolutely necessary? I think of `<Route path="/my/path" view={someView} />` as syntactic sugar for `{actions.router.matches('/my/path') && someView() }`.

**Comment by andyrj** [comment]
I think you need it so that h() passes the routes back as vararg children to the router component that returns the array?  That is what I was figuring at least.

**Comment by zaceno** [comment]
@andyrj, As I understand the concept of "component based router", it's not just meant as a more verbose way of writing an array (that wouldn't be worth much).

I believe idea is to be able to dynamically include/swap components in a view, based on routes. (as opposed to the array-method which only allows you to switch the top level view based on routes)

**Comment by andyrj** [comment]
Wasn't saying you had to simply pass back the array, didn't state that very clear after reading it again.  But the router component would get the routes as children and could then match and render the match or whatever else you want it to do.  

Without a wrapper component how do you know the order they should be matched?  Or if there were two matches and one was more specific which would you render?  I think you run into non-deterministic issues if routes can just be placed wherever and individually evaluate path.  

I am going to keep outta this one, as I don't plan on using this. 🤐

**Comment by andyrj** [comment]
Shouldn't have said return, sorry for confusion there.  I understand what you mean though that would be useless if that is all it was doing.

**Comment by zaceno** [comment]
I understand my misunderstanding now I think. I was thinking of a more explicit type of route matching with no fall-forwards or default et c. Just simple: "if the route looks like this: show this component, if not, don't.

I get it now, that the wrapper is necessary for the sort of sequential matching that the regular router does. 

I think a component style is probably more useful for the type of routing I was thinking of - less for the behaviour of the current router.

**Comment by SkaterDad** [comment]
Is this proposal basically the same as React Router v4's <route> and <switch> components?

Like @zaceno, I'd like a simple `match` function that returns true/false and conditionally renders.  The router mixin would mostly just populate the `state` object and export useful components/utilities.

The one thing I'm unclear on, though, is how we could cleanly handle data fetching on route changes if the routes are all dynamic and not pre-defined.  Anyone tried that yet without using the vdom lifecycle hooks?

**Comment by zaceno** [comment]
From slack talks, I realize that the "normal" type of router, with a matching sequence and wildcard, could work component-style if we have a Switch component. (But the Route component should work as @skaterdad said above when it's not inside a Switch component). 

The thing I wonder how it should work, is how we attach dynamic data (params) to the state, when the Route component is evaluated in the view, i.e. in the render. Updating the state there, will not make the params available to the view on this render - only on the next render.
