### ISSUE TITLE
How to access actions from Components?

### ISSUE THREAD

**Issue by nicolazj** [hyperapp/router#14]
If there is way to access actions from Components, then we can have something like this:
```
 <Link to="/test" >
      Test
 </Link>
```
We don't need to pass in the `actions.router.go` . 

If we want to override default behaviour, then we do 
```
 <Link to="/test"  onclick={...} >
      Test
 </Link>
```

just like the Link components in React Router.

**Comment by jbucaran** [comment]
@nicolazj No, we can't at the moment.

Link is a stateless & functional component and like all other functional components, they can't update their parent unless they are given a function or a mechanism to do so.

In the future, it could be possible for a mixin to register a _view_, just like your app's view. We can then **bind** it to your app's state and actions and give it to you inside the main view.

It might look something like this: (future technology)

```jsx
const Hyperlink = () => ({
  view: (state, actions, props) => {
    props.href = props.to
    props.to = null

    props.onclick = function(element) {
      element.preventDefault()
      actions.go(props.href) // <= We can use actions.go here!
    }

    return h("a", props, props.value)
  }
})

app({
  view: (state, actions, { Hyperlink }) =>
    <main>
       // The rest of the app here!
      <Hyperlink to="/infinity-and-beyond" value="Hyperjump" />
    </main>
})
```

This is not without its warts and there are a few other details we'd need to sort out like the mixin's view function signature; is the one I wrote there the best? or how to share other "widgets" inside a mixin's view if we use the 3rd and 4th argument to pass props and children.

**Comment by valentinbdv** [comment]
+1
