### ISSUE TITLE
Error: Can't resolve './router' with latest npm version

### ISSUE THREAD

**Issue by RikuVan** [hyperapp/router#21]
Upgraded to the latest version and here is no router.js under src, causing this 'Can't resolve '/router' error.

**Comment by jbucaran** [comment]
Steps to reproduce?

Looks good on a fresh install.

<img width="928" alt="screen shot 2017-09-09 at 14 44 22" src="https://user-images.githubusercontent.com/56996/30237463-6899489c-956d-11e7-82d1-b28048b8a3bb.png">

**Comment by jbucaran** [comment]
Cloning, building and testing also works flawlessly.

![](https://user-images.githubusercontent.com/56996/30237477-da2fbfe0-956d-11e7-9d1b-d942db4b84e3.png)

@RikuVan Can you describe what you did?

**Comment by RikuVan** [comment]
<img width="1354" alt="screen shot 2017-09-09 at 11 25 21" src="https://user-images.githubusercontent.com/7317771/30238545-bcb208cc-9551-11e7-9534-7640d61d80f2.png">

**Comment by jbucaran** [comment]
@RikuVan That screenshot without context is not very helpful and this is most likely a problem in your system as I couldn't repro your issue in a fresh install.

Please post the steps to repro the issue and I'll try to help.

**Comment by RikuVan** [comment]
<img width="275" alt="screen shot 2017-09-09 at 11 30 18" src="https://user-images.githubusercontent.com/7317771/30238584-4e4c75a6-9552-11e7-8b7b-446d219e9792.png">

**Comment by RikuVan** [comment]
This is after yarn upgrade @hyperapp/router

**Comment by jbucaran** [comment]
LGTM here: https://unpkg.com/@hyperapp/router@0.3.0/src/

**Comment by RikuVan** [comment]
I understand if you are a bit incredulous when the files appear to all be there. But I tried three times and yarn add @hyperapp/router and every time it arrives with no router.js under src.

**Comment by jbucaran** [comment]
@RikuVan Just for you, I followed the steps:

<img width="1280" alt="screen shot 2017-09-09 at 17 43 18" src="https://user-images.githubusercontent.com/56996/30238675-61e38986-9586-11e7-9f8d-898b5e58b11b.png">

Looks good to me :)

**Comment by RikuVan** [comment]
Yeah I am mystified. Feel free to close because I have no further evidence to offer other than it is not working on my machine. Obviously if you can't reproduce it then that is it. I will ask a friend at work on monday to install out of curiosity.

**Comment by jbucaran** [comment]
Sounds like a problem with yarn maybe? 

Or with your cache. Try using npm. Try installing in a fresh directory too. 🤔👍

**Comment by RikuVan** [comment]
yeah update my version of yarn, cleared the cache, tried npm instead...and still no router.js

**Comment by RikuVan** [comment]
<img width="208" alt="screen shot 2017-09-09 at 12 38 55" src="https://user-images.githubusercontent.com/7317771/30239031-312061ea-955c-11e7-9b00-c039bb672544.png">

**Comment by jbucaran** [comment]
Why do you have a node_modules inside `src`?

**Comment by jbucaran** [comment]
@RikuVan Why do you have a node_modules inside src? That's odd.

**Comment by RikuVan** [comment]
well, this is far fetched but I live in Finland, if I am getting a cached version from npm. But that only makes since if you just updated at some point a version was published without the router.js. I don't suppose that is it.

**Comment by RikuVan** [comment]
yeah, I thought so too. It only has a .yarn-integrity file in it. Maybe part of the new Yarn release?

**Comment by jbucaran** [comment]
The only weird issue with the published router that I know is the file name change from Router to router, but the file was always included, at least according to what I was able to check on unpkg.

**Comment by RikuVan** [comment]
by the way,  I guess the peer dependency for Hyperapp could be updated to the latest version

**Comment by jbucaran** [comment]
Yes, sounds good, but you don't think that could be the issue no?

**Comment by RikuVan** [comment]
no, I don't think so.

**Comment by RikuVan** [comment]
Ok, got up this morning, tried again and, presto, there is the router.js where it is supposed to be :white_check_mark:. Just a long journey to Finland I guess.

**Comment by jbucaran** [comment]
:+1:
