### ISSUE TITLE
A different API.

### ISSUE THREAD

**Issue by JorgeBucaran** [hyperapp/router#27]
@lukejacksonn's #26 and @speier's #23 are the best we have at the moment, but I am still not satisfied with the current approach, so here is (yet) another take on the router's API.

I don't have a PR ready yet, but I wanted to share my ideas right away. Here is an example of how your code would look like.

```js
import router, { Router } from "@hyperapp/router"
```

### Style I

```js
app({
  state: {
    router: router.state
  },
  actions: {
    router: router.actions
  },
  view: Router([["/", indexView], ["/", adventureView]])
})
```
  

### Style II

```js
app({
  state: {
    router: router.state
  },
  actions: {
    router: router.actions
  },
  view: Router([
    {
      path: "/",
      view: indexView
    },
    {
      path: "/",
      view: adventureView
    }
  ])
})
```

**Comment by SkaterDad** [comment]
Your proposed API seems good for simple cases, much like the original built-in router.  It would be great to get something released that actually works so new people aren't put off.

Do you want this package to support more complex use cases, which need guarding/redirects/data/etc...?  Or just keep it simple?

I've got a much more complicated router in the works for my own use cases, which I may end up publishing once my use case is done dictating the API & features..

**Comment by JorgeBucaran** [comment]
@SkaterDad I definitely want to support all of that stuff, let me think how that would look like with this API. 

What would those features be and can you define them?

**Comment by JorgeBucaran** [comment]
@SkaterDad Isn't redirects === guarding? 🤔

**Comment by Swizz** [comment]
`Router` will return a vdom tree, isnt it ? So I will be able to use it into a template ?

```js
app({
  state: {
    router: router.state
  },
  actions: {
    router: router.actions
  },
  view: (state, actions) => main([
    Router([["/", indexView], ["/", adventureView]])(state, actions)
  ])
})
```

**Comment by JorgeBucaran** [comment]
@SkaterDad What is a template?

**Comment by Swizz** [comment]
A wrong name for "used into a vdom tree, as a child"

**Comment by JorgeBucaran** [comment]
@Swizz It returns the view we must give to app() so your app is rendered. So, you don't need to use it like that; it's done for you.

**Comment by Swizz** [comment]
Okay then. I have an header (a nav bar) part of the app. But I only want the Router to deal with the section content. I need to use the header as a stateless component on each view ?
I think that is why both @lukejacksonn and @speier are awaiting Router component.

I think we are not choosing a view to display on a route but if the route match the guard to allow content to be added to the tree.

**Comment by JorgeBucaran** [comment]
@Swizz Sorry, I don't understand what you are saying, but if you show me an example, I could tell you if it works or not.

**Comment by SkaterDad** [comment]
@JorgeBucaran In my mind, the route guard functions can perform both route change cancellation or redirects.  My implementation checks the return value:  string -> redirect, false -> cancel.

The `go` action would check the guard first.  If successful, call the data action (with new route info)

I think you would need to use the object-style API, and allow people to attach `guard` functions and `data` actions.

Rough draft:
```js
app({
  state: {
    testData: null,
    router: router.state
  },
  actions: {
    setTestData: (data) => ({ testData: data })
    router: router.actions
  },
  view: (state, actions) => Router({state, actions}, [
    {
      path: "/",
      view: indexView
    },
    {
      path: "/test",
      guard: (state) => state.authenticated ? true : "/login?return=/test",
      data: (state, data, newRouteInfo) => fetch("/api/test").then(r => r.json()).then(actions.setTestData)
      view: adventureView
    }
  ])
})
```

**Comment by Swizz** [comment]
Okay, Given I am using Hyperapp to do my blog. I have and header to choose sections and articles. If you are on a section I display a list and on an article I display text.

```
import { Router, Link } from "@hyperapp/router"
import * from "@hyperapp/html"
```
```js
view(state, actions) {
  return main([
    header([
      Link({ to: "/article/last" }, "Last"),
      Link({ to: "/section/js" }, "JS articles"),
      Link({ to: "/section/css" }, "CSS articles")
    ]),
    section({ id: "content"}, [
      // Here I want to display content regarding route
    ]),
    footer([
     p("Credits to ...")
    ])
  ])
}
```

**Comment by JorgeBucaran** [comment]
@SkaterDad We could pass `data` into the view function instead.

```js
adventureView: data => state => actions
```

About guards, those are what Luke called redirects in his documentation. Correct?

```js
<Redirect to="/login" when={!state.user} />
```

**Comment by SkaterDad** [comment]
It's similar to his redirect, but you can also return false to prevent the route change to begin with.  

His strategy relies completely on logic in the view, but I prefer the router action to handle it.   Same with data fetching.

**Comment by dmitry-vakhnenko** [comment]
guys guards will be error. Guards forces developers mistakes.

i think component should check `{state.user}`, `{state.user.authorized}`.
+ everybody can wrap admin/authorizedUser specific components in other component-checker.

p.s. i prefer version 2. Its more extensible with clearly syntax. I think it helps in future.

**Comment by SkaterDad** [comment]
> @dmitry-vakhnenko guys guards will be error. Guards forces developers mistakes.

I disagree, but it may be due to our use cases & preferences.

Component-based routing, like Luke's proposal and React Router, are highly dynamic and likely work great for many use cases.

However, some applications need the URL to be like a source of truth, from which you can generate the application state and know which data to fetch.  In React, the library `redux-first-router` embodies this idea.  I'm a big fan of this way, and it's the direction my own routing implementation has gone.  The router itself handles the side effects so the view code remains a pure function.

**Comment by JorgeBucaran** [comment]
@SkaterDad We could have a component-based router if we really want to. 👍  

The issue I am trying to solve is initialization and popstate setup. 

In Elm,  they usually have Html.program, similar to our `app` function. But for routing, they use Navigation.program.

**Comment by JorgeBucaran** [comment]
Let's try the component approach! I'll additional comments to @lukejacksonn's PR.

**Comment by JorgeBucaran** [comment]
Nevermind the comment above. Problems I have with the component router:

- Route is not pure. It uses location.pathname.
  - Passing state.router to every `Route` component is possible, but not very nice.
- Popstate is a bad pattern.

@SkaterDad @lukejacksonn

**Comment by lukejacksonn** [comment]
I look forward to your alternate proposal. Until then I'll push my PR to `hyperapp-router` and work on it from there. Unless you change the view, a component router should work with most versions to come (it should even work on some older versions). 

Too many features have been removed from hyperapp recently, without being substituted with better (or any alternate) solutions, and breaking changes so frequent that the drawbacks are no longer outweighed by the benefits for me to continue championing hyperapp development for anything much more than codepens, prototypes and demos. I've forked a version that works for me and will keep an eye on updates, tweaking my fork and projects if anything good comes along.

**Comment by JorgeBucaran** [comment]
@lukejacksonn I don't have an alternate proposal yet. I like the component approach, but some of the components are not pure, and while I don't hold the view that 100% of all components must be pure, I think the router should set the right example here. 

> Too many features have been removed from hyperapp recently, without being substituted with better (or any alternate) solutions...

Fair enough. I need to follow my plan and you need to follow yours! Good luck in the future! 👋

**Comment by JorgeBucaran** [comment]
@SkaterDad @lukejacksonn Here is a preliminary proposal. Names and minor details are open to change.

```jsx

const homeView = () => (
  <div>
    <h2>Home</h2>
  </div>
)

const aboutView = () => (
  <div>
    <h2>About</h2>
  </div>
)

const topicsView = ({ path }) => ({ match }) => (
  <div>
    <h2>Topics</h2>
    <ul>
      <li>
        <Link to={`${match}/one`}>Hyperapp Topic One</Link>
      </li>
      <li>
        <Link to={`${match}/two`}>Hyperapp Topic Two</Link>
      </li>
      <li>
        <Link to={`${match}/three`}>Hyperapp Topic Three</Link>
      </li>
    </ul>

    <Switch path={match}>
      <Route path={`${match}/:topicId`} view={topicView} />
    </Switch>

    {path === match && <h3>Please select a topic.</h3>}
  </div>
)

const topicView = ({ params }) => (
  <div>
    <h3>{params.topicId}</h3>
  </div>
)

const actions = app({
  state: {
    location: location.state
  },
  actions: {
    location: location.actions
  },
  view: state => (
    <Switch path={state.location.path}>
      <Route path="/home" view={homeView} />
      <Route path="/about" view={aboutView} />
      <Route path="/topics" view={topicsView({ path: state.location.path })} />
    </Switch>
  )
})

location.connect(actions.location)
```

**Comment by SkaterDad** [comment]
@JorgeBucaran Can you give a detailed example of what the objects being passed to the view functions look like?  The terms `path` and `match` are a little hard to distinguish.

**Comment by JorgeBucaran** [comment]
@SkaterDad Sure, keep in mind both the objects and their names are still open to change based on what we actually need. 

The `Switch` component will select the first view that matches `path` and call the function with the route / location / navigation information, in this case the match url.

**Comment by JorgeBucaran** [comment]
@SkaterDad We could get rid of Router and Route and instead go with this:

```jsx
<Navigation
  location={state.location}
  routes={[
    {
      path: "/home",
      view: homeView
    },
    {
      path: "/about",
      view: aboutView
    },
    {
      path: "/topics",
      view: topicsView({ path: state.location.path })
    }
  ]}
/>
```

**Comment by okwolf** [comment]
> @JorgeBucaran The `Switch` component will select the first view that matches `path` and call the function with the route / location / navigation information, in this case the match url.

`Switch` makes me think of a UI component that can be toggled on or off, such as in Material Design: https://material.io/guidelines/components/selection-controls.html#selection-controls-switch

**Comment by JorgeBucaran** [comment]
@okwolf It's gone already. Now it's just `Navigation`.

**Comment by SkaterDad** [comment]
I see what you're doing now.  The example is forgetting to pass `location` to the `topicsView` function, but I imagine it's just `state.location`?

As a component-style router, this looks okay to me.

**Comment by JorgeBucaran** [comment]
@SkaterDad Updated my post to reflect that and renamed Navigation to Router.

**Comment by JorgeBucaran** [comment]
#28
