### ISSUE TITLE
`Switch` evaluates all matching routes

### ISSUE THREAD

**Issue by zaceno** [hyperapp/router#29]
See this example: https://codepen.io/zaceno/pen/MreKjj?editors=0010

Load it with your console open, and notice the log:

```
START SWITCH
nourl Loc...
END SWITCH
```

This is as it should be. It means that the switch checked the `path` of the first route (`/foo`) and saw there was no match. So it moved on to check the second route, which does match (no `path` = always match), and rendered this view

... But now: click the link "FOO" on the page. Takes you to `/foo`. Notice the log: 

```
START SWITCH
withurl Loc...
nourl Loc...
END SWITCH
```

This means that the first route was checked, found to be a match, and the view was rendered.

One expects the switch would stop there. *But it doesn't.*

Not only does it move on to see if the second route matches (which it does, still) but it also *evaluates* the view. (Runs the view function).

**Comment by zaceno** [comment]
Having looked into the code a bit, I realize it's going to be tricky (if not impossible) to achieve the behavior I was expecting, because `Route` can be used standalone as well as in a `Switch`.

So we have to evaluate all renders that match, for the cases when `Route` is *not* inside a `Switch`.

It could work if there was a special `SwitchRoute` component with the same api but specifically for use inside `Switch`:es.... but I don't think anyone wants that.

So for now I think the only option is just to be aware and try to build around it.

**Comment by JorgeBucaran** [comment]
> @zaceno One expects the switch would stop there. But it doesn't.

I am not sure. Why would you expect that?

**Comment by zaceno** [comment]
Because it's supposed to just render and return the first match. Why do more work?

**Comment by JorgeBucaran** [comment]
@zaceno I'll need to look into what ReactRouter's Switch does here. But I think it's the same story there. Temporary answer: "this is by design" and "this is a result of the declarative nature of the design", but maybe we can do better or at least try.

**Comment by zaceno** [comment]
I'd like it if we try, but I think the crux is essentially we would need different behavior for `Route` depending on if it is in a `Switch` or not. And I don't see how that could be possible without a different type of `Route`... maybe with a parameter somehow? Kind of like `parent`?

**Comment by JorgeBucaran** [comment]
Maybe one should only nest routes inside Switch when you know only one of them will match.

**Comment by zaceno** [comment]
@JorgeBucaran that's not possible if you want the "fallback"/"default"/404-route. Since that has to match everything. So anything that matches one of the "proper" routes will also match the default.

**Comment by JorgeBucaran** [comment]
@zaceno Behavior should be the same as ReactRouter IMO.

**Comment by zaceno** [comment]
I think I'll close this. It's rare this issue will rear its head, and there aren't any good fixes I can think of. All one can do is be aware of this if one is in the habit of calling actions immediately in components.
