### ISSUE TITLE
Switch requires JSX to work

### ISSUE THREAD

**Issue by zaceno** [hyperapp/router#30]
See this example:

https://codepen.io/zaceno/pen/OzXxjb?editors=0010

It renders `<h1>Bar</h1>` correctly according to the routing rules.  It uses a view function (`viewJSX`) containing a `<Switch>...</Switch>` in JSX, so it works as it should.

Now comment out `viewJSX` in the app-statement, and un-comment `viewFunc`.  It is the exact same function, only it calls the switch as a function, using `Switch({}, [...])`.

Notice that it doesn't work now. It renders nothing. This is because it is rendering the first result of it's children, which is `false` (because the first child's `path` is not a match for the current location)

JSX filters out falsy children automatically, which is why it works with JSX.

**Comment by JorgeBucaran** [comment]
@zaceno You are on fire! 🔥 

Jut to clarify: wasn't it `Switch({}, ...)` incorrect and `h(Switch)` the preferred way. I can't remember.

I think this is probably a bug anyway, so I'll tag it as such and look into it later.

Thanks for the report! 🙏

**Comment by zaceno** [comment]
>  wasn't it Switch({}, ...) incorrect and h(Switch) the preferred way. I can't remember.

Well, I've never used a function like `h(Component, props, children)`, and haven't seen anyone else do it either that I can remember. It's always `Component(props, children)`. And I much prefer that convention. 

But good point: `h(Switch, {}, child1, child2, child3)` is more accurately how JSX is calling it. And I think 

> JSX filters out falsy children automatically, which is why it works with JSX.

 is probably incorrect. It's `h` that does the filtering.

**Comment by zaceno** [comment]
Fixed!
