### ISSUE TITLE
Not rendering non-exact path

### ISSUE THREAD

**Issue by IniZio** [hyperapp/router#37]
I tried to have `/posts` show a list of posts, then `/posts/abc` to post the detail of post with id abc. However with this code:
```
const view = (state, actions) =>
  h("div", {}, [
    h(Route, {path: '/', render: () => h('div', {}, 'Home')}),
    h(Route, {parent: true, path: '/posts', render: Posts}),
  ])
``
It does not seem it handles `/posts/abc`, since the page goes blank when i go to that route?

**Comment by themastersoda** [comment]
I'd make a parent component for /posts and then inside it check match.params/match.isExact to know what to render

**Comment by zaceno** [comment]
@IniZio Did you try using the `Switch` component?

```
const view = (state, actions) =>
h('div', {}, [
  h(Switch, {}, [
    h(Route, {parent: true, path: '/posts', render: Posts}),
    h(Route, {path: '/', render: () => h('div', {}, 'Home')}),
  ])
])  
```

**Comment by zaceno** [comment]
It's suppost to render only the first matching Route. Not sure if that makes a difference in your case

**Comment by IniZio** [comment]
Thanks in the end it was just me messing up the order of routes 😓. Sorry for disturbing and thanks again for the quick replies!
