### ISSUE TITLE
`oncreate` doesn't get called when you route to a new View

### ISSUE THREAD

**Issue by ForsakenHarmony** [hyperapp/router#38]
I have 2 views, `/` (home) and `/search`.

in search I have `oncreate={actions.search.findNearby}`, this doesn't get called when I route to it from `/`, but it does when I reload the page

**Comment by zaceno** [comment]
It's probably because the vdom engine is repurposing the top elements from the two views. Try setting a different key on the two views top nodes. 

Actually... that will only work if the route components themselves are enclosed in a vnode because keys have no effect on the topmost vnode of an app.

**Comment by ForsakenHarmony** [comment]
uhh, ok?

**Comment by zaceno** [comment]
If my response didn't make sense to you, perhaps you could post a simplified version of the code you have that isn't working, and we can just show you how to make it work.

The problem you're describing is not uncommon and I'm pretty sure it can be solved by keying your different views.

**Comment by ForsakenHarmony** [comment]
Yeah, it worked, I was confused about the second part of what you said, makes sense now though.

Maybe the router could add the path as a key by default

**Comment by ForsakenHarmony** [comment]
misclick, I can make a pr for that if you want it, or you can just close this

**Comment by zaceno** [comment]
> Maybe the router could add the path as a key by default

That's a pretty neat idea! It's the key you'd naturally choose anyway. 

PR away by all means (but it's not my project and I can't speak for anyone else ;) )

**Comment by ForsakenHarmony** [comment]
You're a member ¯\_(ツ)_/¯

**Comment by JorgeBucaran** [comment]
> Maybe the router could add the path as a key by default

How?

@zaceno Could you explain what they are saying? 🙏

**Comment by ForsakenHarmony** [comment]
Just add a `key` to the `Route` with the `path` for the route

**Comment by ForsakenHarmony** [comment]
I found a way

```js
import { parseRoute } from "./parseRoute"

export function Route(props) {
  var location = props.location || window.location
  var match = parseRoute(props.path, location.pathname, {
    exact: !props.parent
  })

  if (!match) return;

  const child = props.render({
		match: match,
		location: location
	});

  child.props.key = child.props.key || props.path;

  return child;
}
```

**Comment by JorgeBucaran** [comment]
@ForsakenHarmony If this works, then I am 💯 in! 

Could you create a PR with tests? 🙏

**Comment by ForsakenHarmony** [comment]
unsure how to test it

**Comment by JorgeBucaran** [comment]
Well, I can think about it then. Feel free to make that PR anyway! 👍
