### ISSUE TITLE
Why should the history APIs be wrapped?

### ISSUE THREAD

**Issue by infinnie** [hyperapp/router#42]
I guess leaving them what they are would be better.

**Comment by JorgeBucaran** [comment]
pushState and replaceState are wrapped to call actions in order to update the state as a result of location changes in the address bar, when the user clicks the back/forward button, etc.

**Comment by infinnie** [comment]
Thanks for explanation, but I do not think that the browser’s internal mechanisms should be altered. Only my opinion

**Comment by JorgeBucaran** [comment]
@infinnie You are welcome to create a new issue/PR with a proposal.
