### ISSUE TITLE
parseRoute question

### ISSUE THREAD

**Issue by willin** [hyperapp/router#43]
https://github.com/willin/router/blob/master/src/parseRoute.js#L28-L41

```js
  for (var i = 0, params = {}, len = paths.length, url = ""; i < len; i++) {
    if (":" === paths[i][0]) {
      try {
        params[paths[i].slice(1)] = urls[i] = decodeURI(urls[i])
      } catch (_) {
        continue
      }
    } else if (paths[i] !== urls[i]) {
      return
    }
    url += urls[i] + "/"
  }

return createMatch(false, path, url.slice(0, -1), params)
```

what does this mean?

**Comment by JorgeBucaran** [comment]
A route is like a template, it can be a static route url like `foo/bar` or dynamic like `foo/bar/:id`. This code finds all the `:id`-like strings inside every path of the route and adds it as a key to the `params` object. 

I still haven't published 1.0, but when I do, I'll brush up this code to make it more readable. There is no need to be golfing with the router like this.

Thanks for bringing it up.
