### ISSUE TITLE
Update view when changing state

### ISSUE THREAD

**Issue by mickeyvip** [hyperapp/router#47]
While playing with `redux-dev-tools` I have noticed that the Router updates the view only as a response to `location` change.

Stepping through the navigation steps was not updating the view.

I think that `location` change should eventually cause the view update, but the "source of truth" should be the state.

**Comment by Mytrill** [comment]
From the source, it looks like the router updates the state as a result of location change: https://github.com/hyperapp/router/blob/48d81a0cca9ce0545905021b1cd78d9d4840a33d/src/location.js#L30

Are you suggesting that the order should be `click link -> state change -> location change -> view updated` rather than `click link -> location change -> state change -> view updated`, or are you saying there is a bug in the implementation?

**Comment by mickeyvip** [comment]
I think that the logic you describe is correct: `location change -> state change -> view update`.

But when only the state changes - the view should also update.

`location` is a side effect, the changes in the `state` should be reflected in the `view` regardless the `location`.

**Comment by Swizz** [comment]
So my first concern should be not looking at how the `state` catch the new `location`, but how a `Link` set a `location` : 
https://github.com/hyperapp/router/blob/48d81a0cca9ce0545905021b1cd78d9d4840a33d/src/Link.js#L22

I tend to use the `view` more like an `update`/`subscribe` point to the `state` changes. So, I would love to see the following pattern.
```
click link -> state change -> location change
                          &-> view render
```

**Comment by mickeyvip** [comment]
Sounds like it will need to handle page refresh differently?

**Comment by Swizz** [comment]
What are you thinking ? Do you agree the API should stay the same ?
If everything is handled by the state, how would you give `history.{go,back,forward}` power to the user ?

**Comment by mickeyvip** [comment]
I think the `location` change should trigger the `stage` change, then `view` change.

But changing `router`'s state (that's what `redux-dev-tools` is doing) should also update the `view`

**Comment by mickeyvip** [comment]
maybe...
`location change` -> (`state change` -> `view change`) 

making 
`state change` -> `view change` just work.

**Comment by Swizz** [comment]
I need more clue, but is this not the current behavior ?

I have not authored the router, but looking at the source code, we have the following pattern.

```
location change -> state change -> view change
```

1. Subscribe to location change
https://github.com/hyperapp/router/blob/48d81a0cca9ce0545905021b1cd78d9d4840a33d/src/location.js#L42

2. Set the location in state at location change
https://github.com/hyperapp/router/blob/48d81a0cca9ce0545905021b1cd78d9d4840a33d/src/location.js#L31-L37

3. Commit state update to call the render view
https://github.com/hyperapp/router/blob/48d81a0cca9ce0545905021b1cd78d9d4840a33d/src/location.js#L26-L28

**Comment by andyrj** [comment]
@mickeyvip can you share a link to the code you have the error with?

**Comment by mickeyvip** [comment]
I didn't look into a code, but the problem is that `view` is not updated when only `state` changes.

**Comment by mickeyvip** [comment]
`set` should be called when only `state` changes.
`state` should change when `location` changes.

**Comment by Swizz** [comment]
From where are you changing the `state.location` ? Another action ?

**Comment by mickeyvip** [comment]
another action, specifically I am using `redux-dev-tools`

**Comment by andyrj** [comment]
Just to clarify why I thought this was issue worthy, the devtools hoa replaces the state in full on time travel.  So if the routes are determined based solely on the state this behavior shouldn't be happening.

**Comment by Swizz** [comment]
Then, now I see where the problem is.

We were looking at the subscription, but the problem is near the consumption. The `view` render is correctly called, but the new expected `Route` is not rendered.

By default, the `Route` renderer is awaiting the `window.location.pathname` to match the `path` parameter.
https://github.com/hyperapp/router/blob/48d81a0cca9ce0545905021b1cd78d9d4840a33d/src/Route.js#L3-L4

This is because in Hyperapp, component are stateless but someone tried to give ease to user using the `Route` component. (cc @JorgeBucaran)

From my seat : You should use the `location` parameter to make your `Route` component strongly related to the `state.location` changes.

```jsx
<Route parent path="/topics" location={state.location} render={TopicsView} />
```

I am not a `redux-devtool` user, can you, please, give it a try for me ?

**Comment by mickeyvip** [comment]
@Swizz, if I am understanding correctly - this is the way

**Comment by Swizz** [comment]
So, we need to document this. This one affect `Route`, `Redirect` and `Link`.

The code is present but the documentation is not.

**Comment by mickeyvip** [comment]
@Swizz, what do you mean by

> the code is present
 
The code also needs a change, right?

**Comment by mickeyvip** [comment]
@Swizz, so just add `location={state.location}`?

I'll give it a try.

Thank you!

**Comment by Swizz** [comment]
So the only need is to clarify this in the documentation.

Do you agree ?

**Comment by mickeyvip** [comment]
@Swizz , just tried it out.. There is a problem.

When I added `location={state.location}` - the page starts reloading when routing...

**Comment by andyrj** [comment]
@mickeyvip did you use e.preventDefault()?

**Comment by andyrj** [comment]
Hang on that is in the Link component...  Hmm, not sure why it's reloading on Link click.

**Comment by mickeyvip** [comment]
@andyrj , just got home and trying it on my hope PC - works! No reloads.

**Comment by Swizz** [comment]
@mickeyvip Does #59 solve this issue on your side ?

**Comment by mickeyvip** [comment]
@Swizz , just checked Hyperapp `1.2.5`, @hyperapp/router `0.5.0`, hyperapp-redux-devtools `1.1.6`. 

It is working as expected with dev tools without additional `location={state.location}`.

**Comment by jorgebucaran** [comment]
@mickeyvip Can we close then? 🎉

**Comment by mickeyvip** [comment]
Yes! Thanks!
