### ISSUE TITLE
How do specified routes get access to the state?

### ISSUE THREAD

**Issue by rexrhino** [hyperapp/router#48]
In the example, we specify the view we want to show via the 'render' parameter:
`<Route path="/" render={Home} />`

Views only appear to be passed a 'match' object, not any state.

In the example, that is fine - but in real life, we are going to want a component that has access to state, because obviously we are going to be showing stuff more complicated than an h2 tag.

What is the proper way to pass the state/actions to the rendered view? And shouldn't the documentation show how to do that, since it is a very basic functionality?

Thanks!

**Comment by JorgeBucaran** [comment]
@rexrhino The way we do it is passing the state and actions (or the parts of the state and actions you want to share with the route) manually.

```js
render={Home(state, actions)} />
```

Don't forget to change the signature of your `Home` component to expect these arguments now.

```js
const Home = (state, actions) => (attributes, children) => VNode
```

Now, this is going to get a lot easier after hyperapp/hyperapp#606 lands and we start sharing the state and actions with components out of the box. 🎉
