### ISSUE TITLE
Lifecycle events for rendered components sometimes don't fire

### ISSUE THREAD

**Issue by jlfgomes** [hyperapp/router#51]
Hey guys, so I don't know if I'm doing something wrong or maybe it's a bug. So, for the following code (which I cut from the README and only added lifecycle event handlers):

```javascript
const Home = () => <h2 oncreate={el => console.log("home created")} ondestroy={el => console.log("home destroyed")}>Home</h2>
const About = () => <h2 oncreate={el => console.log("about created")} ondestroy={el => console.log("about destroyed")}>About</h2>
const Topic = ({ match }) => <h3>{match.params.topicId}</h3>
const TopicsView = ({ match }) => (
  <div oncreate={el => console.log("topics created")} ondestroy={el => console.log("topics destroyed")}>
    <h2>Topics</h2>
    <ul>
      <li>
        <Link to={`${match.url}/components`}>Components</Link>
      </li>
      <li>
        <Link to={`${match.url}/single-state-tree`}>Single State Tree</Link>
      </li>
      <li>
        <Link to={`${match.url}/routing`}>Routing</Link>
      </li>
    </ul>

    {match.isExact && <h3>Please select a topic.</h3>}

    <Route parent path={`${match.path}/:topicId`} render={Topic} />
  </div>
)
```

The rest is exactly the same. When the page loads at `/`, I get `home created` as expected. When I switch from Home to Topics, I get `home destroyed` and `topics created` as expected. However, when I switch from Home to About, I get nothing. If I switch from About to Home, also nothing. Am I missing something?

**Comment by jorgebucaran** [comment]
Hi, @jlfgomes. The routes are returning similar elements, so they are being recycled. To avoid this, you can use a key in the root element of each route to uniquely identify it within its siblings.

**Comment by jlfgomes** [comment]
Yep, that works! Thanks for the reply!

**Comment by jorgebucaran** [comment]
@jlfgomes If that fixes it, can you please close? :)

**Comment by jlfgomes** [comment]
Sorry, I got so excited I forgot to close, lol. Thanks again!

**Comment by willin** [comment]
how to use a key ?

**Comment by Swizz** [comment]
@willin Did you read this part of the documentation https://github.com/hyperapp/hyperapp#keys ?
If this is unclear do not hesitate to ask further questions on Hyperapp issues or Slack.

**Comment by willin** [comment]
oh  i did not notice the readme file updated
