### ISSUE TITLE
CustomEvent not support IE

### ISSUE THREAD

**Issue by zdhxiong** [hyperapp/router#58]
when I use in IE(11 and below), it fails with:
```
location.js (7,1)  Object doesn't support this action
```

**Comment by jorgebucaran** [comment]
@zdhxiong Can you provide more information? This is not enough to help you.

**Comment by zdhxiong** [comment]
@jorgebucaran 
in file: `location.js` line 7, you use `CustomEvent`, but it's compatibility is:
![image](https://user-images.githubusercontent.com/3030330/37754868-41273274-2dde-11e8-927b-1f21cf573f31.png)
I found a polyfill to fix this problem: https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent

**Comment by jorgebucaran** [comment]
@zdhxiong Ah, okay gotcha! Thanks for clarifying.
