### ISSUE TITLE
Deeplinking doesn't work

### ISSUE THREAD

**Issue by niallobrien** [hyperapp/router#74]
Hi, I tried the online demo but when I visit http://hyperapp-router.surge.sh/test directly, I get a 404.

**Comment by jorgebucaran** [comment]
That's an old demo which is entirely a frontend app, no server, hence the 404.

**Comment by niallobrien** [comment]
Hi, is there a new demo? If so, perhaps this should be linked to in the Readme.

**Comment by jorgebucaran** [comment]
@niallobrien The currently linked demo works as it was intended to, but perhaps a slightly more sophisticated demo with a server is what you were looking for? I haven't touched the router for a while and I don't have one at hand, but hop on Slack if you want and ask around.

Disclaimer: I haven't forgotten about the router, I am just busy implementing the new Hyperapp ([2.0](https://github.com/hyperapp/hyperapp/issues/672)). After I am done with that I'll work on the router again. 

👋
