### ISSUE TITLE
Is there a way to have actions inside a route?

### ISSUE THREAD

**Issue by valentinbdv** [hyperapp/router#76]
The most obvious way was to do that : 
```
const Home = (state, actions) => <h2 onclick={()=>actions.down(true)}>Home</h2>
const actions = {
  location: location.actions,
  down: value => state => ({ login: value}),
}
```

I tried many other things but none has worked. Is it possible?

**Comment by jorgebucaran** [comment]
Hi @valentinbdv, I think https://github.com/hyperapp/router/issues/33#issuecomment-354379525 answers your question, but let me know if you meant something else. 👋

**Comment by valentinbdv** [comment]
Yes @jorgebucaran this is what I am looking for.

But can't make it work, do you have a working example please?

I am sorry but I am still getting use to the hyperapp syntax which is quite different from what I am used to.

**Comment by jorgebucaran** [comment]
@valentinbdv Make sure you are using the correct actions which are passed to the view, and not the implementation of your actions which you pass into the app function. Are you doing that perhaps?

**Comment by valentinbdv** [comment]
Ok I just notice my view didn't use the actions as an argument.
Too much copy-paste from other project I think.
Thanks for the help ;)

**Comment by jorgebucaran** [comment]
Great! 🎉 

This is a common problem and it's one of the first things that 2.0 is addressing. 

-  https://github.com/hyperapp/hyperapp/issues/672
-   https://github.com/hyperapp/hyperapp/issues/696

**Comment by jorgebucaran** [comment]
Sure, since you control running the view function, you can pass whatever you want into it. It could be `Login({ state: state.login, actions: actions.login })` or `Login({ foo, bar, baz })`.

**Comment by valentinbdv** [comment]
Not exactly what I imagined but very close to it, putting the children state and actions in a property of the main object did the trick : 
```
const state = {
  user: Login.state
}

const actions = {
  user: Login.actions,
}
```
I had to use "state.user" everywhere in my login view though!

**Comment by jorgebucaran** [comment]
@valentinbdv That's a common pattern in this kind of single-tree architecture. You found it yourself! 😄👍

**Comment by jorgebucaran** [comment]
The single tree architecture is one of the main themes in Hyperapp, so that is not going away. But yeah, 2.0 is a solid step in the right direction.

**Comment by infinnie** [comment]
But if you want to dynamically load actions on a per-route basis for code splitting and reducing initial bundle size, I would suggest my own project: https://github.com/infinnie/hyperapp-connect (npm hyperapp-dynamic-connect).
