### ISSUE TITLE
Fails to re-render on route change if Switch is used as root

### ISSUE THREAD

**Issue by download13** [hyperapp/router#77]
Is [this gist](https://gist.github.com/download13/d65a50a90b2cc44041ea50c6c4f296ab) a Switch is used as the root component in the view. When Switch is used this way, clicking on Link's changes the URL bar, but does not transition to the appropriate route.

Also, I was running that gist with `parcel serve index.html`

**Comment by jorgebucaran** [comment]
@download13 Hmm, yes, I think that makes sense, you need a root node to contain the rendered route.

**Comment by download13** [comment]
This is intended behavior?

**Comment by download13** [comment]
Shouldn't the contents of the current Route be appended to the mount point that was passed to `app()`?

I thought this might require hyperapp to support document fragments, but since the render prop on Route is just a component and components have to return a single vdom node couldn't that single returned node just be passed up through Route and Switch and appended directly to the mount point?

I'm just not clear on why there needs to be a an enclosing root node as long as the view only returns a single Switch component.

**Comment by jorgebucaran** [comment]
@download13 That's not what I see in your gist, or I don't understand what you mean. Your view has no root element.

```jsx
const view = () =>
  <Switch>
    <Route path="/" render={Index} />
    <Route path="/page" render={Page} />
    <Route render={NotFound} />
  </Switch>
```

> I thought this might require hyperapp to support document fragments...

Support for document fragments like React's `<></>` would help and it's being discussed for after 2.0. In the meantime, your view needs a root element.

**Comment by download13** [comment]
I'll try to explain what I mean more clearly:

`Index` returns a valid node.

Can we just pass the result of running/rendering `Index` up to `Route`, which passes it up to `Switch`, which returns it as the root node?

That was what I expected to happen when I wrote the code. That the result of rendering `Index` would be appended to the mount point (`document.body` in this case).

I'm wondering why this is not possible, since if I made my view like this:

```
const view = () => <Index />
```

it would render it's contents into `document.body` without a needing surrounding `<div>` tag.

It also seems like `Switch` does render this way the first time. It just cannot re-render when the location changes.

Is this just a limitation of the way that `Switch` works?

**Comment by jorgebucaran** [comment]
@download13 There is no support for arrays as a root element. Like I explained above, we'd need to use document fragments to support that. But now it seems that's not your problem because each route is wrapped in a div and Switch returns a node, _not_ an array.

This may have to do with lazy components (see https://github.com/hyperapp/router/issues/66), which are currently being used to implement the Switch. This was my mistake and I promise to clean it all up after Hyperapp 2.0 is released.

It may be something else, but I would need to run your code. If you make me a CodePen, then we might be able to move faster with this.

**Comment by download13** [comment]
I can't get it to run on codepen due to conflicts in the assumed path (router thinks it's at /, but codepens are served from a subpath on the site).

I set up a [repo](https://github.com/download13/hyperapp-router-test) where all you need to do to test it is `npm i && npm start`.

**Comment by jorgebucaran** [comment]
@download13 It seems you just forgot to subscribe to location events.

```
// Your code...

const main = app(
  {
    location: location.state
  },
  {
    location: location.actions
  },
  view,
  document.body
);

location.subscribe(main.location)
```

**Comment by download13** [comment]
Ah shoot! That solves it on the test case. And I can no longer replicate the issue in my actual application (though I'm pretty sure it did have it's subscription). So yeah, solved, I guess.

Thanks!

**Comment by jorgebucaran** [comment]
Awesome, glad I could help!
