### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by phongduong** [hyperapp/router#79]
I am working with hyperapp/router but having some problem with <Route />
Whenever i add path prop to `<Route />` like this `<Route path="/dashboard" render={Dashboard} />`, it causes an error and my app crashes. Console prompts this 

> Cannot read property 'length' of undefined

I try to remove path from `<Route />` and app works normally. But i need path to navigate my app. How can i fix it?

**Comment by jorgebucaran** [comment]
Hi @phongduong! Sorry, for the delayed response. 🙇 

 I don't have the problem you are describing. Can you share a CodePen or repo with a reproduction of the problem? It's the only way to help you effectively.

**Comment by phongduong** [comment]
I solved it. Because i split state and actions into modules, i need to import location from router to make it work. Thank you
