### ISSUE TITLE
App crashes when refresing page

### ISSUE THREAD

**Issue by phongduong** [hyperapp/router#80]
I am having problem with refreshing page. When browser loads page initially, app works well. I try to refresh page and app crash. I also test it on router example page, the same result. Do you guys have any solution for it?

**Comment by jorgebucaran** [comment]
@phongduong You need to setup your server to serve `index.html` in every route.

**Comment by phongduong** [comment]
thank you

**Comment by jorgebucaran** [comment]
👍 👍
