### ISSUE TITLE
How to use router in other modules?

### ISSUE THREAD

**Issue by phongduong** [hyperapp/router#82]
I have a question that how i can use router in other modules that is not the main module? For example, if users click log in, i will redirect them to dashboard. When they click log out, they will be to login page. How can i do that?

**Comment by jorgebucaran** [comment]
Are you looking for https://github.com/hyperapp/router#redirect?

Otherwise, I recommend you share a CodePen or example repository reproducing you're having.

**Comment by jorgebucaran** [comment]
@phongduong Thanks for the sandbox, now if you could walk me through the code and explain what you tried to do and failed, or what you want to do in more detail, that would help me _help_ you.

Also, could you clarify what you mean by other modules?  

Cheers!

**Comment by phongduong** [comment]
This app is simple. You click login button, it sets `state.authenticated` to true and redirects to path `/`. When you click log out, it back to login page. You can see i create `<PrivateRoute />` to check if user was authenticated.
Other modules are `Dashboard` and `Login`. I want to split components into modules to keep code clean.

**Comment by jorgebucaran** [comment]
@phongduong And what's the problem?

**Comment by jorgebucaran** [comment]
Your codebox has a syntax error, if you can fix it, that would be great.

**Comment by phongduong** [comment]
I fixed and updated my present code

**Comment by jorgebucaran** [comment]
It seems to be working. When I click "Log in" it jumps to the Dashboard and when I click "Log out" it jumps back to Login.

**Comment by phongduong** [comment]
I know. But can i use `<Redirect />` to do it?

**Comment by jorgebucaran** [comment]
You are using Redirect. I see Redirect being used in two parts of the code.

**Comment by jorgebucaran** [comment]
It appears you just need some help, and there are actually not bugs in the Router this time. If you need help with something, I suggest you join us on Slack as I want to use the issue tracker to track issues, bugs, feature requests, etc.
