### ISSUE TITLE
Link active class ?

### ISSUE THREAD

**Issue by lili21** [hyperapp/router#86]
something like this

```jsx
<Link to="/hello" active="active">Hello</Link>
```

will add `active` class to the element when the path match the link.

**Comment by jorgebucaran** [comment]
@lili21 What are you doing?

**Comment by jorgebucaran** [comment]
@lili21 I highly recommend you [join our slack](http://hyperappjs.herokuapp.com/). Cheers.

**Comment by zaceno** [comment]
If you've wired the router state to the `location` namespace in your app, I think this should work:

```
<Link to="/hello" class={state.location.pathname==="/hello" ? "active" : ""}>Hello</Link>
```
