### ISSUE TITLE
State returns only match and location?

### ISSUE THREAD

**Issue by dblodorn** [hyperapp/router#87]
Hi! So happy there is an official router for hyperapp - just starting to refresh my portfolio with hyperapp and hope to use for future projects, really love the overall simplicity!!!

One hangup I'm having is retrieving my app state in route components.

So when I try to reference state in a View (Page) all i get is an object with match and location:

`{match: {…}, location: {…}}`

Any thoughts as to how this could be happening?
-- Many thanks in advance!

[Example site: (state is being output in console)](https://stage.dmbk.io/)

[Repo](https://github.com/dblodorn/dmbk-2018)

Code below:

index.js

```
import withReduxDevtools from '@frontmen/hyperapp-redux-devtools'
import { location } from '@hyperapp/router'
import { app } from 'hyperapp'
import { state, actions } from './state'
import App from './App'

const main = withReduxDevtools(app)(
  state,
  actions, 
  App,
  document.body
)

location.subscribe(main.location)
```

App Comonent:
```
export default (state, actions) =>
    <Main oncreate={() => actions.getApiData()}>
      <Nav>
        <NavLink to="/">Home</NavLink>
        <NavLink to="/about">About</NavLink>
      </Nav>
      <FullRule/>
      <Switch>
        <Route path="/" render={Home} />
        <Route path="/about" render={About}/>
        <Route render={NotFound} />
      </Switch>
    </Main>
```

View Component - Home:

```
export default (state) => {
  console.log(state) // Just returns object with match & location, nothing else in my state.
  return (
    <section>
      <H1>Dain Blodorn Kim</H1>
    </section>
  )
}
```

**Comment by zaceno** [comment]
@dblodorn that's actually expected behavior for the router. It's not expected to pass the state  as the first argument but *props*, and the props it passes are `location` and `match`.

So what you want to do is define your routed components like this:

```jsx
export default (state, actions) => ({location, match}) => {
  console.log(state) // Just returns object with match & location, nothing else in my state.
  return (
    <section>
      <H1>Dain Blodorn Kim</H1>
    </section>
  )
}
```

And define your routes like this:

```jsx
<Switch>
        <Route path="/" render={Home(state, actions)} />
        <Route path="/about" render={About(state, actions)}/>
        <Route render={NotFound(state, actions)} />
</Switch>
```

Does that make sense?

**Comment by dblodorn** [comment]
@zaceno Awesome thanks! this makes sense. Coming from react redux, vue vuex - so was under the assumption that i could access state from anywhere (like with connect react-redux) - thanks a mil for the helpful advice.

Loving Hyperapp (esp. having a 7k bundle with styling, router, state management, transitions... etc! Insane!!!💥💥💥)

**Comment by zaceno** [comment]
@dblodorn When you mentioned connect react-redux I just realised I totally forgot about the feature called connected components (alternatively "lazy components"). Now, it's on it's way out in the next version of Hyperapp, but in version 1.2.x you could actually keep your main file as you had it, and just define your routed components as:

```jsx
export default ({location, match}) => (state, actions) => {
  console.log(state) // Just returns object with match & location, nothing else in my state.
  return (
    <section>
      <H1>Dain Blodorn Kim</H1>
    </section>
  )
}
```

don't know how I forgot about this 🙃 

Anyway, like I said, it's on its way out, and somewhat discouraged. (Esp since there are more explicit, unmagical solutions). But at least you know :)

**Comment by slacktracer** [comment]
@zaceno Are you sure it works? I mean, I was trying it here just now and if something like:
```
<Switch>
        <Route path="/" render={Home(state, actions)} />
        <Route path="/about" render={About(state, actions)}/>
        <Route render={NotFound(state, actions)} />
</Switch>
```

it seems my components will be forever stuck with original state and will not receive the current state on every route render...

**Comment by zaceno** [comment]
@slacktracer I haven’t tried it in forever but I don’t know why it wouldn’t work. 

When the state is changed the entire view is recalculated, meaning the values of the render props is also recalculated.
