### ISSUE TITLE
"A route without a path is always a match." ?

### ISSUE THREAD

**Issue by urbanhop** [hyperapp/router#90]
The Readme on Routes says

> A route without a path is always a match. 

I do not understand hat.

**Comment by jorgebucaran** [comment]
@urbanhop It's confusing, I agree. It means, however, that if you omit the `path` attribute, the route will always match, meaning the component specified via the `render` attribute will be rendered.

The following route is rendered oInly if path equals "/".
```jsx
<Route path="/" render={Home} />
```

The following route is always rendered.
```jsx
<Route render={Home} /> 
```
